### PR TITLE
hot-reloading

### PR DESCRIPTION
**Pull request by stoeffel**
### Reviewer asks
* How should I include the license of elm-hot https://github.com/klazuka/elm-hot/blob/master/LICENSE.txt?

### CODE REVIEW

**Comment by rtfeldman** [comment]
Regarding the license, I'd just add it to the end of `LICENSE` - something like "Jetpack uses code from _______________ which has this license: ___________________"

**Comment by lukewestby** [comment]
Is this a correct summary of the change?

> Jetpack bundles `hmr.js` from the original elm-hot, which is designed for Webpack. It wraps compiled Elm output with a custom implementation of Webpack's hot module API that uses `eval` on incoming code. Jetpack starts a WebSocket server to which the wrapped Elm module connects on start. The WebSocket server has a configurable port. Starting Jetpack in hot mode is done with the `--hot` flag.

**Comment by stoeffel** [comment]
@lukewesby yes

**Comment by lukewestby** [comment]
Daaaaaaamn, that's cool. Publish away!

ap_bruins_flyers_hockey

**Pull request merged**
