### PR TITLE
Ormolu

### PR DESCRIPTION
**Pull request by asterite**
This installs [ormolu](https://github.com/tweag/ormolu) via nix (depends on #85) and then formats all files.

To format all files I did:

```
$ find src | grep .hs | xargs -L1 ormolu --mode inplace
```

💭  Maybe we should have a script or some way to run ormolu, but maybe it's not necessary if editors are going to format files automatically.

### CODE REVIEW

**Comment by stoeffel** [comment]
Looks great! I think having a script (or shake?) would be nice and running it with `--mode check` on travis.

**Comment by asterite** [comment]
I'm going to try with shake so I code more in Haskell :-)

**Comment by asterite** [comment]
Maybe we can merge this and tackle Shakefile + checking in another PR because it involves a lot of steps (installing shake with nix, adding Shakefile, rules, etc.)

**Comment by asterite** [comment]
I also just find out there's [script./hindent.sh](https://github.com/NoRedInk/jetpack/blob/master/script/hindent.sh) already so another approach is to update that script.

**Pull request merged**
